FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o choubis cmd/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/choubis .
EXPOSE 9000
CMD ["./choubis"]
